# Generated by Django 2.0.5 on 2018-08-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='OurUsers',
        ),
    ]
